version: "v2.20.0"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=recipe
    ports:
      - '5432:5432'

  recipe:
    container_name: file-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/arafindb
      - SPRING_DATASOURCE_USERNAME=arafin
      - SPRING_DATASOURCE_PASSWORD=arafinN@123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db